# Generated by Django 5.1.6 on 2025-02-21 21:17

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField(validators=[api.validators.validate_publication_date])),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('summary', models.TextField(max_length=100)),
            ],
        ),
    ]
